import { useEffect, useRef, useState } from "react";
import { ArrowRight, Bot, Check, Cloud, FileText, LockKeyhole, Mail, MessageSquareText, ShieldCheck, Sparkles } from "lucide-react";
import { agents, defaultLandingContent, LandingContentData, integrations, projects, securityItems, timeline } from "../content/landingContent";
import { toast } from "sonner";
import { submitProjectRequest } from "../content/siteContent";

export function SectionHeader({ eyebrow, title, body, light = false }: { eyebrow: string; title: React.ReactNode; body?: string; light?: boolean }) {
  return <div className={`section-header ${light ? "light" : ""}`}><span>{eyebrow}</span><h2>{title}</h2>{body && <p>{body}</p>}</div>;
}

function Reveal({ children, className = "" }: { children: React.ReactNode; className?: string }) {
  const ref = useRef<HTMLDivElement>(null);
  useEffect(() => { const node = ref.current; if (!node) return; const io = new IntersectionObserver(([e]) => e.isIntersecting && node.classList.add("is-visible"), { threshold: .12 }); io.observe(node); return () => io.disconnect(); }, []);
  return <div ref={ref} className={`scroll-reveal ${className}`}>{children}</div>;
}

export function ProductShowcase({ items: _items = defaultLandingContent.productCategories }: { items?: LandingContentData["productCategories"] }) {
  const [active, setActive] = useState(0);
  const tools = [
    { name: "Microsoft", mark: "M", color: "#f25022", x: 12, y: 50 },
    { name: "Outlook", mark: "O", color: "#0078d4", x: 23, y: 20 },
    { name: "Google Calendar", mark: "31", color: "#4285f4", x: 50, y: 9 },
    { name: "Gmail", mark: "M", color: "#ea4335", x: 77, y: 20 },
    { name: "Google Drive", mark: "D", color: "#0f9d58", x: 88, y: 50 },
    { name: "Slack", mark: "S", color: "#36c5f0", x: 77, y: 80 },
    { name: "GitHub", mark: "GH", color: "#24292f", x: 50, y: 91 },
    { name: "Teams", mark: "T", color: "#6264a7", x: 23, y: 80 },
  ];
  useEffect(() => { const timer = window.setInterval(() => setActive(value => (value + 1) % tools.length), 3600); return () => window.clearInterval(timer); }, [tools.length]);
  return <section id="platform" className="section workspace-section"><div className="section-inner"><Reveal><SectionHeader eyebrow="The intelligent workspace" title={<>Everything connected.<br />One intelligent center.</>} body="AK Cloud connects the systems your teams already use and keeps context moving between them." /></Reveal><div className="integration-system"><svg className="system-lines" viewBox="0 0 1000 650" preserveAspectRatio="none" aria-hidden="true">{tools.map((tool, i) => <g key={tool.name} className={active === i ? "active" : ""}><line x1={tool.x * 10} y1={tool.y * 6.5} x2="500" y2="325" /><circle r="4"><animateMotion dur={`${2.8 + i * .12}s`} repeatCount="indefinite" path={`M ${tool.x * 10} ${tool.y * 6.5} L 500 325`} /></circle></g>)}</svg><div className="system-radar"><i /><i /><i /></div><div className="integration-nodes" role="tablist" aria-label="Connected systems">{tools.map((tool, i) => <button role="tab" aria-selected={active === i} key={tool.name} onClick={() => setActive(i)} className={`integration-node ${active === i ? "active" : ""}`} style={{ "--node-x": `${tool.x}%`, "--node-y": `${tool.y}%`, "--node-color": tool.color, "--node-delay": `${i * -.4}s` } as React.CSSProperties}><span>{tool.mark}</span><b>{tool.name}</b></button>)}</div><div className="system-agent" key={active}><div className="google-ring" /><div className="system-agent-core"><Bot /><small>AK CLOUD</small><strong>AGENT</strong></div><div className="agent-connection"><i /> Connected to <b>{tools[active].name}</b></div></div></div></div></section>;
}

export function HumanAISection() {
  return <section id="solutions" className="section human-ai"><div className="section-inner"><Reveal><SectionHeader eyebrow="Human + AI" title="AI that works where your people work." body="AK Cloud follows the flow of work, connects the context, and handles the small handoffs that slow teams down." /></Reveal><div className="human-grid"><div className="human-photo human-video"><video autoPlay muted loop playsInline preload="metadata" poster="/assets/akcloud-team-hero.png" aria-label="A product team collaborating in a modern office"><source src="/assets/akcloud-team-collaboration.mp4" type="video/mp4" /></video><div className="photo-note"><MessageSquareText /><span><b>Stand-up complete</b><small>Context captured with permission</small></span></div><span className="video-live"><i /> LIVE WORKFLOW</span></div><div className="workflow-timeline">{timeline.map(([time, label], i) => <div className="timeline-row" key={time}><time>{time}</time><span className={i === 0 ? "human-dot" : "ai-dot"}>{i === 0 ? <Check /> : <Sparkles />}</span><div><small>{i === 0 ? "TEAM" : "AK CLOUD"}</small><strong>{label}</strong></div></div>)}</div></div></div></section>;
}

export function AgentsSection() { return <section id="agents" className="section agents-section"><div className="section-inner"><Reveal><SectionHeader light eyebrow="AK Cloud agents" title="Give your work an AI workforce." body="Purpose-built agents work across the tools and context your teams already rely on—with people guiding what happens next." /></Reveal><div className="agent-grid">{agents.map(({ name, icon: Icon, description, tools, status }) => <article className="agent-card" key={name}><div className="agent-top"><span><Icon /></span><i>{status}</i></div><h3>{name}</h3><p>{description}</p><div><small>CONNECTED TO</small><div className="tool-list">{tools.map(tool => <span key={tool}>{tool}</span>)}</div></div></article>)}</div><a className="text-link light" href="#contact">Explore Agents <ArrowRight /></a></div></section> }

export function IntegrationGrid() { return <section id="integrations" className="section integrations-section"><div className="section-inner"><Reveal><SectionHeader eyebrow="Connect everything" title={<>Your tools.<br />One intelligence layer.</>} body="Bring context together without asking teams to abandon the software they know." /></Reveal><div className="integration-grid">{integrations.map((name, i) => <div className="integration-tile" key={name}><span className={`neutral-logo logo-${i % 4}`}>{name.split(" ").map(w => w[0]).join("").slice(0,2)}</span><b>{name}</b><small>Connected</small></div>)}</div></div></section> }

export function KnowledgeDiagram() { return <section id="resources" className="section knowledge-section"><div className="section-inner"><Reveal><SectionHeader eyebrow="Connected knowledge" title="Your company’s knowledge should work for you." body="AK Cloud grounds AI in the information your teams already trust, retrieving the right context before it generates an answer or takes action." /></Reveal><div className="rag-labels"><span>01 · INGEST</span><span>02 · RETRIEVE + GROUND</span><span>03 · RESPOND + ACT</span></div><div className="knowledge-diagram"><div className="knowledge-side inputs">{["PDF", "Docs", "Meeting notes", "Projects", "Emails"].map(x => <span key={x}><FileText />{x}</span>)}</div><div className="knowledge-core"><i><Cloud /></i><small>AK CLOUD</small><strong>KNOWLEDGE + RAG</strong><p>Permission-aware retrieval</p><div className="rag-pulse"><span /><span /><span /></div></div><div className="knowledge-side outputs">{["Grounded answers", "Relevant context", "Recommendations", "Approved actions"].map(x => <span key={x}><Sparkles />{x}</span>)}</div></div><p className="rag-caption"><ShieldCheck /> Sources stay permission-aware. Every response is grounded in workspace context before it reaches your team.</p></div></section> }

export function SecuritySection() { return <section id="security" className="section security-section"><div className="section-inner security-layout"><div><SectionHeader light eyebrow="Enterprise control" title={<>Your intelligence.<br />Under your control.</>} body="AK Cloud is designed around clear access boundaries. We distinguish what works today from capabilities still on the roadmap." /><div className="security-seal"><ShieldCheck /><span><b>Control stays with your team</b><small>Human approval where it matters</small></span></div></div><div className="security-list">{securityItems.map(([label, status]) => <div key={label}><span><LockKeyhole />{label}</span><i className={status === "Roadmap" ? "planned" : ""}>{status}</i></div>)}</div></div></section> }

export function ProductStory() { const steps = ["Sachin starts a meeting", "AK Cloud captures context", "Agent identifies tasks", "Project tools get updated", "Calendar follow-up created", "Team receives summary"]; return <section className="section story-section"><div className="section-inner"><div className="story-frame"><img src="/assets/akcloud-product-story.png" alt="Professionals discussing priorities in a meeting" /><div className="story-shade" /><div className="story-title"><span>A day with AK Cloud</span><h2>Good work keeps moving.</h2></div><div className="story-flow">{steps.map((s, i) => <div key={s}><span>{i + 1}</span><p>{s}</p>{i < steps.length - 1 && <i />}</div>)}</div></div></div></section> }

export function ProjectPortfolio() {
  const renderProjects = (duplicate = false) => <div className="project-track-group" aria-hidden={duplicate || undefined}>{projects.map(project => <article className="project-marquee-card" key={`${duplicate ? "copy-" : ""}${project.number}`}><span className="marquee-number">{project.number}</span><div><small>{project.category}</small><h3>{project.name}</h3><p>{project.summary}</p></div><i className={`project-status status-${project.status.toLowerCase()}`}><span />{project.status}</i><ArrowRight /></article>)}</div>;
  return <section id="projects" className="project-marquee-section" aria-label="Selected AK Cloud projects"><div className="project-marquee-heading"><span>SELECTED PROJECTS</span><p>What we’re building with connected intelligence</p></div><div className="project-marquee" role="region" aria-label="Scrolling project portfolio"><div className="project-marquee-track">{renderProjects()}{renderProjects(true)}</div></div></section>
}

export function CTASection() {
  const submit = async (event: React.FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = event.currentTarget; const data = new FormData(form); try { await submitProjectRequest({ requestType: data.get("requestType") as "demo" | "project", name: String(data.get("name") || ""), email: String(data.get("email") || ""), company: String(data.get("company") || ""), message: String(data.get("message") || "") }); toast.success("Thanks — your request has been sent to the AK Cloud team."); form.reset(); } catch (error) { toast.error(error instanceof Error ? error.message : "Unable to send request"); } };
  return <section id="contact" className="section cta-section"><div className="cta-orbit" /><div className="section-inner request-layout"><div className="request-copy"><span>LET’S CONNECT THE WORK</span><h2>See what AK Cloud can do for your team.</h2><p>Request a tailored demo or tell us about the project you’re planning. We’ll come prepared with a useful next step.</p><div className="request-promise"><Check /><small>No sales script. A focused conversation about your workflow.</small></div></div><form className="request-form" onSubmit={submit}><div className="request-type"><label><input type="radio" name="requestType" value="demo" defaultChecked /><span>Request a demo</span></label><label><input type="radio" name="requestType" value="project" /><span>Discuss a project</span></label></div><div className="request-fields"><label><span>Name</span><input required name="name" placeholder="Your name" /></label><label><span>Work email</span><input required name="email" type="email" placeholder="you@company.com" /></label></div><label><span>Company</span><input required name="company" placeholder="Company name" /></label><label><span>What would you like to improve?</span><textarea required name="message" rows={4} placeholder="Tell us about your team, workflow, or project…" /></label><button type="submit">Send request <ArrowRight /></button><small>By submitting, you agree that the AK Cloud team may contact you about this request.</small></form></div></section>
}

export function Footer() { return <footer className="new-footer"><div className="section-inner"><div className="footer-brand"><a href="#home"><img src="/brand/ak-cloud-experience.png" alt="AK Cloud experience" /></a><p>Intelligence for the way<br />people actually work.</p></div><div className="footer-columns"><div><b>Platform</b><a href="#platform">Workspace</a><a href="#agents">AI Agents</a><a href="#integrations">Integrations</a></div><div><b>Company</b><a href="#security">Security</a><a href="#contact">Contact</a><a href="/admin">Admin</a></div><div><b>Connect</b><a href="mailto:sachin06012018@gmail.com"><Mail /> sachin06012018@gmail.com</a><span>India · Working globally</span></div></div><div className="footer-bottom"><span>© {new Date().getFullYear()} AK Cloud Enterprise</span><span><i /> Systems operational</span></div></div></footer> }
